import random
nombres_femeninos_MX = ("Abigail","Abril","Agustina","Alaia","Alana","Alba","Luz","Alejandra","Alicia","Alma","Altagracia","Amala","Amalia","Amanda","Ana","Ana Carolina","Ana Lucía","Ana María","Ana Patricia","Ana Sofía","Andrea","Ángeles","Antonella","Antonia","Ariana","Ashley","Bárbara","Beatriz","Belén","Briana","Brithany","Camila","Caridad","Carmen","Carmen Luisa","Carolina","Catalina","Celeste","Claudia","Concepción","Daniela","Danna","Dayana","Del Carmen","Delfina","Domenica","Dulce María","Elizabeth","Emilia","Emily","Emma","Esmeralda","Evelyn","Florencia","Francesca/Francisca","Gabriela","Génesis","Guadalupe","Isabella","Isidora","Jimena","Josefa","Josefina","Juana","Julia","Julieta","Kamila","Karla","Karla Patricia","Kiara","Kimberly","Laura","Leticia","Lidia","Lisandra","Liz","Luana","Lucía","Luciana","Luisa","Luisa Fernanda","Luz","Luz María","Mabel","Maite","Margarita","María","María Ángeles","María Carmen","María Celeste","María del Carmen","María Dolores","María Elena","María Fernanda","María Isabel","María Jesús","María José","María Luisa","María Paula","María Teresa","Mariana","Mariangel","Mariapaz","Maritza","Martha","Martina","Mayelin","Melany","Mercedes","Mia","Mikaela","Morena","Noemí","Odalys","Olga Marina","Olivia","Patricia","Paula","Ramona","Raquel","Reina Isabel","Rosa","Rosmery","Roxana","Salomé","Samantha","Sara Sofía","Sara Valentina","Silvia","Sofía","Sonia","Sophia","Tania","Teresa","Trinidad","Valentina","Valeria","Vanessa","Verónica","Victoria","Ximena","Yadira","Yaima","Yamileth","Yanelis","Yanet","Zoe")
nombres_masculinos_MX =("Adrián","Agustín","Alberto","Alejandro","Alexander","Alexis","Alonso","Andrés Felipe","Ángel","Anthony","Antonio","Bautista","Benicio","Benjamín","Carlos","Carlos Alberto","Carlos Eduardo","Carlos Roberto","César","Cristóbal","Daniel","David","Diego","Dylan","Eduardo","Emiliano","Emmanuel","Enrique","Erik","Ernesto","Ethan","Fabián","Facundo","Felipe","Félix","Félix María","Fernando","Francisco","Francisco Javier","Gabriel","Gaspar","Gustavo Adolfo","Hugo","Ian","Iker","Isaac","Jacob","Javier","Jayden","Jeremy","Jerónimo","Jesús","Jesús Antonio","Jesús Víctor","Joaquín","Jorge","Jorge Alberto","Jorge Luis","José","José Antonio","José Daniel","José David","José Francisco","José Gregorio","José Luis","José Manuel","José Pablo","Josué","Juan","Juan Ángel","Juan Carlos","Juan David","Juan Esteban","Juan Ignacio","Juan José","Juan Manuel","Juan Pablo","Juan Sebastián","Julio","Julio Cesar","Justin","Kevin","Lautaro","Liam","Lian","Lorenzo","Lucas","Luis","Luis Alberto","Luis Emilio","Luis Fernando","Manuel","Manuel Antonio","Marco Antonio","Mario","Martín","Mateo","Matías","Maximiliano","Maykel","Miguel","Miguel Ángel","Nelson","Noah","Oscar","Pablo","Pedro","Rafael","Ramón","Raúl","Ricardo","Rigoberto","Roberto","Rolando","Samuel","Samuel David","Santiago","Santino","Santos","Sebastián","Thiago","Thiago Benjamín","Tomás","Valentino","Vicente","Víctor","Víctor Hugo")
nombres_masculinos_USA = ("James","John","Robert","Michael","William","David","Joseph","Richard","Charles","Thomas","Christopher","Daniel","Matthew","George","Anthony","Donald","Paul","Mark","Andrew","Edward","Steven","Kenneth","Joshua","Kevin","Brian","Ronald","Timothy","Jason","Jeffrey","Jacob","Ryan","Frank","Nicholas","Gary","Eric","Stephen","Jonathan","Larry","Justin","Raymond","Scott","Samuel","Benjamin","Brandon","Gregory","Jack","Henry","Alexander","Patrick","Walter","Dennis","Jerry","Tyler","Aaron","Peter","Jose","Adam","Douglas","Nathan","Harold","Zachary","Arthur","Carl","Albert","Kyle","Lawrence","Joe","Willie","Gerald","Roger","Jeremy","Ethan","Keith","Christian","Terry","Harry","Jesse","Sean","Austin","Noah","Ralph","Roy","Louis","Bruce","Billy","Bryan","Eugene","Jordan","Dylan","Russell","Gabriel","Wayne","Alan","Juan","Howard","Vincent","Logan","Fred","Philip","Randy","Victor","Bobby","Johnny","Martin","Phillip","Elijah","Bradley","Shawn","Travis","Clarence","Ernest","Stanley","Craig","Mason","Leonard","Carlos","Isaac","Caleb","Earl","Jimmy","Francis","Cody","Danny","Cameron","Todd","Luke","Dale","Luis","Alex","Nathaniel","Evan","Joel","Allen","Lucas","Frederick","Curtis","Norman","Marvin","Theodore","Antonio","Jackson","Tony","Glenn","Rodney","Melvin","Adrian","Edwin","Alfred","Hunter","Steve")
nombres_femeninos_USA = ("Mary","Elizabeth","Patricia","Jennifer","Linda","Barbara","Margaret","Susan","Dorothy","Sarah","Jessica","Helen","Nancy","Betty","Karen","Lisa","Anna","Sandra","Emily","Ashley","Kimberly","Donna","Ruth","Carol","Michelle","Laura","Amanda","Melissa","Rebecca","Stephanie","Deborah","Sharon","Kathleen","Cynthia","Amy","Emma","Shirley","Angela","Catherine","Virginia","Katherine","Brenda","Pamela","Frances","Nicole","Christine","Evelyn","Samantha","Alice","Rachel","Janet","Carolyn","Debra","Martha","Maria","Marie","Heather","Diane","Julie","Joyce","Grace","Victoria","Rose","Joan","Christina","Kelly","Olivia","Lauren","Ann","Doris","Julia","Jean","Judith","Kathryn","Mildred","Lillian","Cheryl","Hannah","Megan","Andrea","Sara","Jacqueline","Teresa","Gloria","Janice","Theresa","Madison","Judy","Beverly","Abigail","Charlotte","Jane","Denise","Marilyn","Amber","Danielle","Sophia","Diana","Brittany","Natalie","Ruby","Irene","Annie","Isabella","Lori","Kayla","Alexis","Tiffany","Florence","Kathy","Louise","Lois","Tammy","Crystal","Bonnie","Taylor","Phyllis","Anne","Erin","Ella","Josephine","Alyssa","Allison","Shannon","Eleanor","Edna","Peggy","Tina","Robin","Dawn","Audrey","Rita","Clara","Wanda","Ava","Ethel","Paula","Norma","Ellen","Marjorie","Eva","Jamie","Leslie","Edith","Connie","Gladys","Carrie","Hazel","Valerie","Wendy")
apellidos_mixtos = ("Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez ","Lopez","Gonzales","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers","Gutierrez","Ortiz","Morgan","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos","Kim","Cox","Ward","Richardson","Watson","Brooks","Chavez","Wood","James","Bennet","Gray","Mendoza","Ruiz","Hughes","Price","Alvarez","Castillo","Sanders","Patel","Myers","Long","Ross","Foster","Jimenez")
nombres_masculinos = nombres_masculinos_USA+nombres_masculinos_MX
nombres_femeninos = nombres_femeninos_USA+nombres_femeninos_MX
sexo = 1
nombre = ""
apellido1 = ""
apellido2 = ""
sexo = random.randint(0,1)
if sexo ==  1:#mujer
	nombre = random.choice(nombres_femeninos)
if sexo ==  0:#hombre 
	nombre = random.choice(nombres_masculinos)
apellido1 = random.choice(apellidos_mixtos)
apellido2 = random.choice(apellidos_mixtos)	
print(nombre,apellido1,apellido2)
#curl thispersondoesnotexist.com

